doctrine:
    orm:
        metadata_cache_driver:
            type: service
            id: cache.system
        query_cache_driver:
            type: service
            id: cache.system
        result_cache_driver:
            type: service
            id: cache.app

services:
    doctrine.result_cache_pool:
        alias: cache.app
        public: false

    doctrine.system_cache_pool:
        alias: cache.system
        public: false

framework:
    cache:
        pools:
            doctrine.result_cache_pool:
                adapter: cache.app
            doctrine.system_cache_pool:
                adapter: cache.system
